# --- Backend ---
# Tente "glx" para melhor performance com placas de vídeo.
# Se bugar, mude para "xrender".
backend = "xrender";
vsync = true;
glx-no-stencil = true;
glx-copy-from-front = false;

# --- Opacidade ---
active-opacity = 1.0;
inactive-opacity = 0.95;
frame-opacity = 1.0;
inactive-opacity-override = false;

# Regras de opacidade específica (Exemplo para o Kitty)
opacity-rule = [

];

# --- Blur (Desfoque no fundo da barra e janelas) ---
blur: {
  method = "dual_kawase";
  strength = 6;
  background = true;
  background-frame = false;
  background-fixed = false;
}

# Impede que o blur bugue em algumas janelas
blur-background-exclude = [
  "window_type = 'dock'",
  "window_type = 'desktop'",
  "_GTK_FRAME_EXTENTS@:c"
];

# --- Sombras (Shadows) ---
shadow = true;
shadow-radius = 12;
shadow-offset-x = -12;
shadow-offset-y = -12;
shadow-opacity = 0.5;

shadow-exclude = [
  "name = 'Notification'",
  "class_g = 'Polybar'",
  "class_g = 'i3-frame'",
  "_GTK_FRAME_EXTENTS@:c"
];

# --- Fading (Transições suaves) ---
fading = true;
fade-in-step = 0.03;
fade-out-step = 0.03;
fade-delta = 5;
