general {
    lock_cmd = pidof hyprlock || hyprlock       # comando para bloquear
    before_sleep_cmd = loginctl lock-session    # bloquear antes de suspender
    after_sleep_cmd = hyprctl dispatch dpms on  # ligar a tela ao acordar
}

listener {
    timeout = 300                                # 5 minutos
    on-timeout = loginctl lock-session           # bloqueia a sessão
}

listener {
    timeout = 330                                # 5.5 minutos
    on-timeout = hyprctl dispatch dpms off       # apaga o monitor
    on-resume = hyprctl dispatch dpms on         # acende ao voltar
}
