[colors]
; Fundo e Primeiro Plano
background = #282c34
background-alt = #373e4d
foreground = #abb2bf
primary = #61afef
secondary = #e06c75
alert = #be5046
disabled = #707880

; Cores do Accent
red = #e06c75
orange = #d19a66
yellow = #e5c07b
green = #98c379
cyan = #56b6c2
blue = #61afef
purple = #c678dd