font_family     JetBrainsMono Nerd Font 

font_size 12.0

background_opacity 0.8

term xterm-kitty

scrollback_lines 2000

enable_audio_bell no

tab_bar_min_tabs            1
tab_bar_edge                bottom
tab_bar_style               powerline
tab_powerline_style         slanted
tab_title_template          {title}{' :{}:'.format(num_windows) if num_windows > 1 else ''}

term xterm-256color

map kitty_mod+t new_tab
map cmd+t       new_tab
map ctrl+enter new_tab

map crtl+shift+w close_os_window

map ctrl+alt+t set_tab_title

enabled_layouts splits,stack,tall,fat
map ctrl+h launch --cwd=current --location=hsplit
map ctrl+v launch --cwd=current --location=vsplit

map ctrl+1 goto_tab 1
map ctrl+2 goto_tab 2
map ctrl+3 goto_tab 3
map ctrl+4 goto_tab 4

shell /usr/bin/zsh

include current-theme.conf
